version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test
  
  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    
    steps:
      - checkout
         
      - run:
          command: |
            git config --global user.email "lopes.leandrorj@gmail.com"
            git config --global user.name "lopesleandrorj"
            git add .
            git commit -m "[skip ci ci] Generated Build"
            npm version patch -m "[skip ci ci] Bumped version number to %s"
            git push origin master
            git push --tags

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - dev
      - deploy:
          requires:
            - build