version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test
  
  deploy:
    machine:
        enabled: true

    environment:
      CURRENT_BRACH: dev

    working_directory: ~/repo
    
    steps:
      - checkout  
      - run:
          command: |
            git clone git@github.com:lopesleandrorj/calculator.git calculator
            cd ./calculator
            git config --global user.email "circleci"
            git config --global user.name "circleci"
            git push --set-upstream origin master
            git pull origin dev
            git add .
            git status
            git commit -m "[skip ci] test"
            git push

            
            


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
      - deploy:
          requires:
            - build