version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test
  
  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    
    steps:
      - checkout
         
      - run:
          command: |
            git push

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build