version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test
  
  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    
    steps:
      - checkout
      - add_ssh_keys:
        fingerprints:
          - "0e:fe:cf:af:19:f3:76:99:92:03:a1:a8:84:48:b5:d6"
         
      - run:
          command: |
            git config --global user.email "lopes.leandrorj@gmail.com"
            git config --global user.name "lopesleandrorj"
            git init
            git remote set-url origin git@github.com:lopesleandrorj/calculator.git
            git checkout master
            git pull origin dev
            git add .
            git commit -m "New deploy"
            git push

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - dev
      - deploy:
          requires:
            - build