version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test
  
  deploy:
    machine:
        enabled: true

    environment:
      CURRENT_BRACH: dev

    working_directory: ~/repo
    
    steps:
      - checkout  
      - run:
          command: |
            git branch -D master
            git clone git@github.com:lopesleandrorj/calculator.git calculator
            cd ./calculator
            git config --global user.email "lopes.leandrorj@gmail.com"
            git config --global user.name "lopesleandrorj"
            git branch -a
            git checkout master
            ls -la
            git checkout --track origin/master
            git merge dev

            
            


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - master
      - deploy:
          requires:
            - build