version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node
    
    working_directory: ~/repo

    steps:
      - checkout
      - run: npm install
      - run: npm test
  
  deploy:
    machine:
        enabled: true
    working_directory: ~/repo
    
    steps:    
      - run:
          command: |
            git clone git@github.com:lopesleandrorj/calculator.git calculator
            cd ./calculator
            git config --global user.email "lopes.leandrorj@gmail.com"
            git config --global user.name "lopesleandrorj"
            git branch -a
            git push remotes/origin/dev:remotes/origin/master

            
            


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
        filters:
          branches:
            only:
              - dev
      - deploy:
          requires:
            - build